{{- if or .Values.rbac.create .Values.rbac.existingClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gateway-monitor.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gateway-monitor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  {{- if .Values.rbac.create }}
  name: {{ include "gateway-monitor.fullname" . }}
  {{- else }}
  name: {{ .Values.rbac.existingClusterRole }}
  {{- end }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
